# Generated by Django 5.2.6 on 2025-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalreport',
            options={'ordering': ['-date'], 'verbose_name': 'Medical Report', 'verbose_name_plural': 'Medical Reports'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Timeline Event', 'verbose_name_plural': 'Timeline Events'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visit_date', '-visit_time'], 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterModelOptions(
            name='vitalreading',
            options={'ordering': ['-date'], 'verbose_name': 'Vital Reading', 'verbose_name_plural': 'Vital Readings'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='personal_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['personal_number', 'surname'], name='medical_rec_persona_5d0836_idx'),
        ),
    ]
