# Generated by Django 5.2.6 on 2025-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_alter_medicalreport_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='pain_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
