# Generated by Django 5.2.6 on 2025-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_vitalreading_comment_vitalreading_oxygen_saturation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='rbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='patient',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='recorded_by',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
