# Generated by Django 5.2.6 on 2025-09-17 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_vitalreading_rbs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='medical_records.patient'),
        ),
        migrations.CreateModel(
            name='ConsultationRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='available', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('specialty_focus', models.CharField(blank=True, max_length=100, null=True)),
                ('total_consultations_today', models.IntegerField(default=0)),
                ('average_consultation_time', models.IntegerField(blank=True, null=True)),
                ('last_patient', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='medical_records.patient')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='medical_records.user')),
            ],
            options={
                'verbose_name': 'Consultation Room',
                'verbose_name_plural': 'Consultation Rooms',
                'db_table': 'consultation_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vitals_data', models.JSONField(blank=True, null=True)),
                ('lab_orders', models.JSONField(blank=True, null=True)),
                ('prescriptions', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('rescheduled_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='medical_records.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='medical_records.consultationroom')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='medical_records.user')),
            ],
            options={
                'verbose_name': 'Consultation Session',
                'verbose_name_plural': 'Consultation Sessions',
                'db_table': 'consultation_sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
