# Generated by Django 5.2.6 on 2025-09-17 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_user_alter_vitalreading_patient_consultationroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationroom',
            name='queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
