# Generated by Django 5.2.6 on 2025-09-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_dependent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='medical_records.patient'),
        ),
    ]
