# Generated by Django 5.2.6 on 2025-09-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_medication_visit_consultation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='available_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='out_of_stock_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.user'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
